from pydantic import BaseModel


class Error(BaseModel):
    code: int
    message: str


# class ModelParams(BaseModel):
#     name: str
#     response_format: Optional[Any] = None
#     toolcall_parser_version: Optional[str] = None
#     parallel_tool_calls: bool = True
#     infer_kwargs: dict[str, Any] = {}
#
#
# class Function(BaseModel):
#     arguments: str | None = None
#     """
#     The arguments to call the function with, as generated by the model in JSON
#     format. Note that the model does not always generate valid JSON, and may
#     hallucinate parameters not defined by your function schema. Validate the
#     arguments in your code before calling your function.
#     """
#
#     name: str | None = None
#     """The name of the function to call."""
#
#
# class ChatToolCall(BaseModel):
#     index: int | None = None
#     """The index of the tool call."""
#
#     id: str | None = None
#     """The ID of the tool call."""
#
#     function: Function
#     """The function that the model called."""
#
#     type: str | None = "function"
#     """The type of the tool. Currently, only `function` is supported."""
#
#
# class ChatMessage(BaseModel):
#     id: Optional[str] = None
#     role: Optional[str] = None
#     content: str | list[dict] | None = None
#     tool_call_id: Optional[str] = None
#     tool_calls: Optional[list[ChatToolCall]] = None
#
#     # for train use
#     extra_info: Optional[dict] = None
#
#
# class LLMRequest(BaseModel):
#     messages: list[ChatMessage]
#     model: ModelParams
